# Generated by Django 3.1.1 on 2021-02-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(default='', max_length=250, verbose_name='facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=250, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.CharField(default='', max_length=250, verbose_name='github'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(default='', max_length=250, verbose_name='linkedin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(default='', max_length=250, verbose_name='twitter'),
            preserve_default=False,
        ),
    ]
