# Generated by Django 3.1.1 on 2021-03-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210228_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('F', 'Frontend'), ('B', 'Backend'), ('D', 'Devops'), ('V', 'Video Gamer Developer'), ('UIX', 'UI/UX'), ('DB', 'Data Base Developer'), ('CC', 'Cloud Computing')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
